openapi: 3.1.0
info:
  title: Demo API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /basketball:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-basketball
  /football:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-football
components:
  schemas: {}
